version: '3.8'

services:
  python_app:
    build:
      context: ../../..
      dockerfile:  Documents/bot421/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - redbot421

networks:
  redbot421:
    driver: bridge
