version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 2462128990
      MYSQL_DATABASE: flaskmysql
    ports:
      - "3307:3306"
    networks:
      - redbot421

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - redbot421

networks:
  mynetwork:
    driver: bridge

