name: Test Docker Connection

on:
  push:
    branches:
      - main

jobs:
  test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Test Docker connection
        run: docker --version